Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'controller')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Controller', src, depend = ['RT_USING_CONTROLLER'], CPPPATH = CPPPATH)

Return('group')
