Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
platform.c
stm32f4xx_it.c
drv_usart.c
""")

# add Ethernet drivers.
#if GetDepend('RT_USING_LWIP'):
#    src += ['stm32f4xx_eth.c']

# add gpio drivers.
if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

# add sdio drivers.
if GetDepend('RT_USING_SDIO'):
	src += ['drv_sdio.c']

# add spi drivers.
if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']

# add iic drivers.
if GetDepend('RT_USING_I2C'):
	src += ['drv_i2c.c']

# add adc drivers.
if GetDepend('RT_USING_ADC'):
	src += ['drv_adc.c']

# add camera drivers.
if GetDepend('RT_USING_CAMERA'):
    src += ['drv_dcmi.c']
    if GetDepend('CAMERA_USING_OV2640'):
        src += ['ov2640.c']

#add motor drivers.
if GetDepend('RT_USING_MOTOR'):
    if GetDepend('MOTOR_USING_DC_MOTOR'):
        src += ['hbridge.c']
    if GetDepend('MOTOR_USING_SERVO'):
        src += ['mg995.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

